import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

import 'package:forui/forui.dart';

// ignore_for_file: unnecessary_ignore
// ignore_for_file: avoid_redundant_argument_values

/// Generated by Forui CLI.
///
/// Modify the generated function bodies to create your own custom style.
/// Then, call the modified functions and pass the results to your FThemeData.
///
/// ### Example
/// Generated style:
/// ```dart
/// // Modify this function's body.
/// FDividerStyles dividerStyles({
///   required FColorScheme color,
///   required FStyle style,
/// }) => FDividerStyles(
///   horizontalStyle: FDividerStyle(
///     colors: colors.secondary,
///     padding: FDividerStyle.defaultPadding.horizontalStyle,
///     width: style.borderWidth,
///   ),
///   verticalStyle: FDividerStyle(
///     colors: colors.secondary,
///     padding: FDividerStyle.defaultPadding.verticalStyle,
///     width: style.borderWidth,
///   ),
/// );
/// ```
///
/// File that contains your `FThemeData`:
/// ```dart
/// import 'package:my_application/theme/divider_style.dart' // Your generated style file.
///
/// FThemeData(
///  color: FThemes.zinc.light.color,
///  style: FThemes.zinc.light.style,
///  dividerStyles: CustomFDividerStyles.dividerStyles( // The function in your generated style file.
///    color: FThemes.zinc.light.color,
///    style: FThemes.zinc.light.style,
///   ),
/// );
/// ```
///
/// A theme can be generated using the Forui CLI:
/// ```shell
/// dart forui theme create [theme name]
/// ```
///
/// See https://forui.dev/docs/themes#customize-themes for more information.
FCheckboxStyle checkboxStyle({required FColors colors, required FStyle style}) {
  final label = _labelStyles(style: style).horizontalStyle;
  return .new(
    tappableStyle: style.tappableStyle.copyWith(motion: FTappableMotion.none),
    focusedOutlineStyle: style.focusedOutlineStyle.copyWith(
      borderRadius: .circular(4),
    ),
    iconStyle: FWidgetStateMap({
      WidgetState.selected & WidgetState.error: IconThemeData(
        color: colors.errorForeground,
        size: 14,
      ),
      WidgetState.selected & ~WidgetState.disabled: IconThemeData(
        color: colors.primaryForeground,
        size: 14,
      ),
      WidgetState.selected & WidgetState.disabled: IconThemeData(
        color: colors.disable(colors.primaryForeground),
        size: 14,
      ),
    }),
    decoration: FWidgetStateMap({
      WidgetState.error & WidgetState.selected: BoxDecoration(
        borderRadius: style.borderRadius,
        color: colors.error,
      ),
      WidgetState.error: BoxDecoration(
        borderRadius: style.borderRadius,
        border: .all(color: colors.error, width: 0.6),
        color: colors.background,
      ),
      WidgetState.disabled & WidgetState.selected: BoxDecoration(
        borderRadius: style.borderRadius,
        color: colors.disable(colors.primary),
      ),
      WidgetState.disabled: BoxDecoration(
        borderRadius: style.borderRadius,
        border: .all(color: colors.disable(colors.primary), width: 0.6),
        color: colors.disable(colors.background),
      ),
      WidgetState.selected: BoxDecoration(
        borderRadius: style.borderRadius,
        color: colors.primary,
      ),
      WidgetState.any: BoxDecoration(
        borderRadius: style.borderRadius,
        border: .all(color: colors.primary, width: 0.6),
        color: colors.background,
      ),
    }),
    labelTextStyle: style.formFieldStyle.labelTextStyle,
    descriptionTextStyle: style.formFieldStyle.descriptionTextStyle,
    errorTextStyle: style.formFieldStyle.errorTextStyle,
    labelPadding: label.labelPadding,
    descriptionPadding: label.descriptionPadding,
    errorPadding: label.errorPadding,
    childPadding: label.childPadding,
  );
}

FLabelStyles _labelStyles({required FStyle style}) => FLabelStyles(
  horizontalStyle: .inherit(
    style: style,
    descriptionPadding: const .only(top: 2),
    errorPadding: const .only(top: 2),
    childPadding: const .symmetric(horizontal: 8),
  ),
  verticalStyle: .inherit(
    style: style,
    labelPadding: const .only(bottom: 5),
    descriptionPadding: const .only(top: 5),
    errorPadding: const .only(top: 5),
  ),
);
