// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/settings_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 2042981092780694625),
    name: 'SettingsModel',
    lastPropertyId: const obx_int.IdUid(5, 112760356675095212),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5241689308822684120),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2197491941694432934),
        name: 'githubToken',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6849134407261031137),
        name: 'settingJsonPath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4406205544201717028),
        name: 'lastSync',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 112760356675095212),
        name: 'repositoryId',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 2042981092780694625),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    SettingsModel: obx_int.EntityDefinition<SettingsModel>(
      model: _entities[0],
      toOneRelations: (SettingsModel object) => [],
      toManyRelations: (SettingsModel object) => {},
      getId: (SettingsModel object) => object.id,
      setId: (SettingsModel object, int id) {
        object.id = id;
      },
      objectToFB: (SettingsModel object, fb.Builder fbb) {
        final githubTokenOffset = object.githubToken == null
            ? null
            : fbb.writeString(object.githubToken!);
        final settingJsonPathOffset = fbb.writeString(object.settingJsonPath);
        final repositoryIdOffset = object.repositoryId == null
            ? null
            : fbb.writeString(object.repositoryId!);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, githubTokenOffset);
        fbb.addOffset(2, settingJsonPathOffset);
        fbb.addInt64(3, object.lastSync?.millisecondsSinceEpoch);
        fbb.addOffset(4, repositoryIdOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final lastSyncValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          10,
        );
        final object = SettingsModel()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..githubToken = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 6)
          ..settingJsonPath = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 8, '')
          ..lastSync = lastSyncValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(lastSyncValue)
          ..repositoryId = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 12);

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [SettingsModel] entity fields to define ObjectBox queries.
class SettingsModel_ {
  /// See [SettingsModel.id].
  static final id = obx.QueryIntegerProperty<SettingsModel>(
    _entities[0].properties[0],
  );

  /// See [SettingsModel.githubToken].
  static final githubToken = obx.QueryStringProperty<SettingsModel>(
    _entities[0].properties[1],
  );

  /// See [SettingsModel.settingJsonPath].
  static final settingJsonPath = obx.QueryStringProperty<SettingsModel>(
    _entities[0].properties[2],
  );

  /// See [SettingsModel.lastSync].
  static final lastSync = obx.QueryDateProperty<SettingsModel>(
    _entities[0].properties[3],
  );

  /// See [SettingsModel.repositoryId].
  static final repositoryId = obx.QueryStringProperty<SettingsModel>(
    _entities[0].properties[4],
  );
}
